macro(copy_target_dlls TARGET)
add_custom_command(TARGET ${TARGET} POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_RUNTIME_DLLS:${TARGET}> $<TARGET_FILE_DIR:${TARGET}>
  COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_PDB_FILE:${TARGET}> $<TARGET_FILE_DIR:${TARGET}>
  COMMAND_EXPAND_LISTS
)
endmacro(copy_target_dlls)